### PR TITLE
Chore: CI and dev tools

### LINKED ISSUE #1: Configure CI and dev tools for this repository
- [ ] enable travis for this repository
- [ ] add rustfmt.toml
- [ ] add Travis config
- [ ] add Travis badge to README

### PR DESCRIPTION
**Pull request by amanjeev**
Resolves #1 

chore: fixes SHELF issue https://github.com/sos-os/shelf/issues/1 "Configure CI and dev tools for this repository #1"

chore: adds rustfmt.toml for the project.

chore: updates .gitignore

feat: adds barebones travis.yml

chore: adds travis build status badge

### CODE REVIEW

**Comment by amanjeev** [comment]
Fails for obvious reasons, not sure if we should merge your branch with actual changes first.

**Review by hawkw — APPROVED** [review]
This looks good to me --- thanks a lot! 👍  

As you said, the build failure is expected since we've not pushed any actual code to master yet. Let's go ahead and merge this regardless, and then I can rebase my dev branch off of it.

**Review by hawkw — CHANGES_REQUESTED** [review]
Let's *not* actually push a Cargo.toml to master in this branch, as that will caus merge conflicts when I merge f6a04e64b8e2e9896eaff68d6b031089347378b1

**Comment by amanjeev** [comment]
I reverted the change for `Cargo.toml`.  I do not have permissions to merge (not that I need them lol).

**Review by hawkw — APPROVED** [review]

**Comment by hawkw** [comment]
thanks @amanjeev, this looks good!

**Pull request merged**
